//  request tft gamingpc laptops accessories graphicscard computerparts
export const TFT_LIST_REQUEST = "TFT_LIST_REQUEST"
export const TFT_LIST_SUCCESS = "TFT_LIST_SUCCESS"
export const TFT_LIST_FAIL = "TFT_LIST_FAIL"

export const GAMINGPC_LIST_REQUEST = "GAMINGPC_LIST_REQUEST"
export const GAMINGPC_LIST_SUCCESS = "GAMINGPC_LIST_SUCCESS"
export const GAMINGPC_LIST_FAIL = "GAMINGPC_LIST_FAIL"

export const LAPTOP_LIST_REQUEST = "LAPTOP_LIST_REQUEST"
export const LAPTOP_LIST_SUCCESS = "LAPTOP_LIST_SUCCESS"
export const LAPTOP_LIST_FAIL = "LAPTOP_LIST_FAIL"

export const ACCESSORIES_LIST_REQUEST = "ACCESSORIES_LIST_REQUEST"
export const ACCESSORIES_LIST_SUCCESS = "ACCESSORIES_LIST_SUCCESS"
export const ACCESSORIES_LIST_FAIL = "ACCESSORIES_LIST_FAIL"

export const GRAPHICSCARD_LIST_REQUEST = "GRAPHICSCARD_LIST_REQUEST"
export const GRAPHICSCARD_LIST_SUCCESS = "GRAPHICSCARD_LIST_SUCCESS"
export const GRAPHICSCARD_LIST_FAIL = "GRAPHICSCARD_LIST_FAIL"

export const COMPUTERPARTS_LIST_REQUEST = "COMPUTERPARTS_LIST_REQUEST"
export const COMPUTERPARTS_LIST_SUCCESS = "COMPUTERPARTS_LIST_SUCCESS"
export const COMPUTERPARTS_LIST_FAIL = "COMPUTERPARTS_LIST_FAIL"

// details tft gamingpc laptops accessories graphicscard computerparts
export const TFT_DETAILS_REQUEST = "TFT_DETAILS_REQUEST"
export const TFT_DETAILS_SUCCESS = "TFT_DETAILS_SUCCESS"
export const TFT_DETAILS_FAIL = "TFT_DETAILS_FAIL"

export const GAMINGPC_DETAILS_REQUEST = "GAMINGPC_DETAILS_REQUEST"
export const GAMINGPC_DETAILS_SUCCESS = "GAMINGPC_DETAILS_SUCCESS"
export const GAMINGPC_DETAILS_FAIL = "GAMINGPC_DETAILS_FAIL"

export const LAPTOP_DETAILS_REQUEST = "LAPTOP_DETAILS_REQUEST"
export const LAPTOP_DETAILS_SUCCESS = "LAPTOP_DETAILS_SUCCESS"
export const LAPTOP_DETAILS_FAIL = "LAPTOP_DETAILS_FAIL"

export const ACCESORIES_DETAIL_REQUEST = "ACCESSORIES_DETAILS_REQUEST"
export const ACCESORIES_DETAIL_SUCCESS = "ACCESSORIES_DETAILS_SUCCESS"
export const ACCESORIES_DETAIL_FAIL = "ACCESSORIES_DETAILS_FAIL"

export const GRAPHICSCARD_DETAILS_REQUEST = "GRAPHICSCARD_DETAILS_REQUEST"
export const GRAPHICSCARD_DETAILS_SUCCESS = "GRAPHICSCARD_DETAILS_SUCCESS"
export const GRAPHICSCARD_DETAILS_FAIL = "GRAPHICSCARD_DETAILS_FAIL"

export const COMPUTERPARTS_DETAILS_REQUEST = "COMPUTERPARTS_DETAILS_REQUEST"
export const COMPUTERPARTS_DETAILS_SUCCESS = "COMPUTERPARTS_DETAILS_SUCCESS"
export const COMPUTERPARTS_DETAILS_FAIL = "COMPUTERPARTS_DETAILS_FAIL"

// CREATE TFT GAMINGPC LAPTOPS ACCESSORIES GRAPHICSCARD COMPUTERPARTS
export const CREATE_TFT_REQUEST = "CREATE_TFT_REQUEST"
export const CREATE_TFT_SUCCESS = "CREATE_TFT_SUCCESS"
export const CREATE_TFT_FAIL = "CREATE_TFT_FAIL"
export const CREATE_TFT_RESET = "CREATE_TFT_RESET"

export const CREATE_GAMINGPC_REQUEST = "CREATE_GAMINGPC_REQUEST"
export const CREATE_GAMINGPC_SUCCESS = "CREATE_GAMINGPC_SUCCESS"
export const CREATE_GAMINGPC_FAIL = "CREATE_GAMINGPC_FAIL"
export const CREATE_GAMINGPC_RESET = "CREATE_GAMINGPC_RESET"

export const CREATE_LAPTOP_REQUEST = "CREATE_LAPTOP_REQUEST"
export const CREATE_LAPTOP_SUCCESS = "CREATE_LAPTOP_SUCCESS"
export const CREATE_LAPTOP_FAIL = "CREATE_LAPTOP_FAIL"
export const CREATE_LAPTOP_RESET = "CREATE_LAPTOP_RESET"

export const CREATE_ACCESSORIES_REQUEST = "CREATE_ACCESSORIES_REQUEST"
export const CREATE_ACCESSORIES_SUCCESS = "CREATE_ACCESSORIES_SUCCESS"
export const CREATE_ACCESSORIES_FAIL = "CREATE_ACCESSORIES_FAIL"
export const CREATE_ACCESSORIES_RESET = "CREATE_ACCESSORIES_RESET"

export const CREATE_GRAPHICSCARD_REQUEST = "CREATE_GRAPHICSCARD_REQUEST"
export const CREATE_GRAPHICSCARD_SUCCESS = "CREATE_GRAPHICSCARD_SUCCESS"
export const CREATE_GRAPHICSCARD_FAIL = "CREATE_GRAPHICSCARD_FAIL"
export const CREATE_GRAPHICSCARD_RESET = "CREATE_GRAPHICSCARD_RESET"

export const CREATE_COMPUTERPARTS_REQUEST = "CREATE_COMPUTERPARTS_REQUEST"
export const CREATE_COMPUTERPARTS_SUCCESS = "CREATE_COMPUTERPARTS_SUCCESS"
export const CREATE_COMPUTERPARTS_FAIL = "CREATE_COMPUTERPARTS_FAIL"
export const CREATE_COMPUTERPARTS_RESET = "CREATE_COMPUTERPARTS_RESET"

// UPDATE TFT GAMINGPC LAPTOPS ACCESSORIES GRAPHICSCARD COMPUTERPARTS
export const UPDATE_TFT_REQUEST = "UPDATE_TFT_REQUEST"
export const UPDATE_TFT_SUCCESS = "UPDATE_TFT_SUCCESS"
export const UPDATE_TFT_FAIL = "UPDATE_TFT_FAIL"
export const UPDATE_TFT_RESET = "UPDATE_TFT_RESET"

export const UPDATE_GAMINGPC_REQUEST = "UPDATE_GAMINGPC_REQUEST"
export const UPDATE_GAMINGPC_SUCCESS = "UPDATE_GAMINGPC_SUCCESS"
export const UPDATE_GAMINGPC_FAIL = "UPDATE_GAMINGPC_FAIL"
export const UPDATE_GAMINGPC_RESET = "UPDATE_GAMINGPC_RESET"

export const UPDATE_LAPTOP_REQUEST = "UPDATE_LAPTOP_REQUEST"
export const UPDATE_LAPTOP_SUCCESS = "UPDATE_LAPTOP_SUCCESS"
export const UPDATE_LAPTOP_FAIL = "UPDATE_LAPTOP_FAIL"
export const UPDATE_LAPTOP_RESET = "UPDATE_LAPTOP_RESET"

export const UPDATE_ACCESSORIES_REQUEST = "UPDATE_ACCESSORIES_REQUEST"
export const UPDATE_ACCESSORIES_SUCCESS = "UPDATE_ACCESSORIES_SUCCESS"
export const UPDATE_ACCESSORIES_FAIL = "UPDATE_ACCESSORIES_FAIL"
export const UPDATE_ACCESSORIES_RESET = "UPDATE_ACCESSORIES_RESET"

export const UPDATE_GRAPHICSCARD_REQUEST = "UPDATE_GRAPHICSCARD_REQUEST"
export const UPDATE_GRAPHICSCARD_SUCCESS = "UPDATE_GRAPHICSCARD_SUCCESS"
export const UPDATE_GRAPHICSCARD_FAIL = "UPDATE_GRAPHICSCARD_FAIL"
export const UPDATE_GRAPHICSCARD_RESET = "UPDATE_GRAPHICSCARD_RESET"

export const UPDATE_COMPUTERPARTS_REQUEST = "UPDATE_COMPUTERPARTS_REQUEST"
export const UPDATE_COMPUTERPARTS_SUCCESS = "UPDATE_COMPUTERPARTS_SUCCESS"
export const UPDATE_COMPUTERPARTS_FAIL = "UPDATE_COMPUTERPARTS_FAIL"
export const UPDATE_COMPUTERPARTS_RESET = "UPDATE_COMPUTERPARTS_RESET"

// DELETE TFT GAMINGPC LAPTOPS ACCESSORIES GRAPHICSCARD COMPUTERPARTS

export const DELETE_TFT_REQUEST = "DELETE_TFT_REQUEST"
export const DELETE_TFT_SUCCESS = "DELETE_TFT_SUCCESS"
export const DELETE_TFT_FAIL = "DELETE_TFT_FAIL"
export const DELETE_TFT_RESET = "DELETE_TFT_RESET"

export const DELETE_GAMINGPC_REQUEST = "DELETE_GAMINGPC_REQUEST"
export const DELETE_GAMINGPC_SUCCESS = "DELETE_GAMINGPC_SUCCESS"
export const DELETE_GAMINGPC_FAIL = "DELETE_GAMINGPC_FAIL"
export const DELETE_GAMINGPC_RESET = "DELETE_GAMINGPC_RESET"

export const DELETE_LAPTOP_REQUEST = "DELETE_LAPTOP_REQUEST"
export const DELETE_LAPTOP_SUCCESS = "DELETE_LAPTOP_SUCCESS"
export const DELETE_LAPTOP_FAIL = "DELETE_LAPTOP_FAIL"
export const DELETE_LAPTOP_RESET = "DELETE_LAPTOP_RESET"

export const DELETE_ACCESSORIES_REQUEST = "DELETE_ACCESSORIES_REQUEST"
export const DELETE_ACCESSORIES_SUCCESS = "DELETE_ACCESSORIES_SUCCESS"
export const DELETE_ACCESSORIES_FAIL = "DELETE_ACCESSORIES_FAIL"
export const DELETE_ACCESSORIES_RESET = "DELETE_ACCESSORIES_RESET"

export const DELETE_COMPUTERPARTS_REQUEST = "DELETE_COMPUTERPARTS_REQUEST"
export const DELETE_COMPUTERPARTS_SUCCESS = "DELETE_COMPUTERPARTS_SUCCESS"
export const DELETE_COMPUTERPARTS_FAIL = "DELETE_COMPUTERPARTS_FAIL"
export const DELETE_COMPUTERPARTS_RESET = "DELETE_COMPUTERPARTS_RESET"

export const DELETE_GRAPHICSCARD_REQUEST = "DELETE_GRAPHICSCARD_REQUEST"
export const DELETE_GRAPHICSCARD_SUCCESS = "DELETE_GRAPHICSCARD_SUCCESS"
export const DELETE_GRAPHICSCARD_FAIL = "DELETE_GRAPHICSCARD_FAIL"
export const DELETE_GRAPHICSCARD_RESET = "DELETE_GRAPHICSCARD_RESET"

// check token validation
export const CHECK_TOKEN_VALID_REQUEST = "CHECK_TOKEN_VALID_REQUEST"
export const CHECK_TOKEN_VALID_SUCCESS = "CHECK_TOKEN_VALID_SUCCESS"
export const CHECK_TOKEN_VALID_FAIL = "CHECK_TOKEN_VALID_FAIL"
export const CHECK_TOKEN_VALID_RESET = "CHECK_TOKEN_VALID_RESET"
// user login/logout
export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST"
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS"
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL"
export const USER_LOGOUT = "USER_LOGOUT"

// user registration/signup
export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST"
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS"
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL"

// user info/details
export const USER_DETAILS_REQUEST = "USER_DETAILS_REQUEST"
export const USER_DETAILS_SUCCESS = "USER_DETAILS_SUCCESS"
export const USER_DETAILS_FAIL = "USER_DETAILS_FAIL"

// user update details
export const UPDATE_USER_DETAILS_REQUEST = "UPDATE_USER_DETAILS_REQUEST"
export const UPDATE_USER_DETAILS_SUCCESS = "UPDATE_USER_DETAILS_SUCCESS"
export const UPDATE_USER_DETAILS_FAIL = "UPDATE_USER_DETAILS_FAIL"
export const UPDATE_USER_DETAILS_RESET = "UPDATE_USER_DETAILS_RESET"

// delete user account
export const DELETE_USER_ACCOUNT_REQUEST = "DELETE_USER_ACCOUNT_REQUEST" 
export const DELETE_USER_ACCOUNT_SUCCESS = "DELETE_USER_ACCOUNT_SUCCESS" 
export const DELETE_USER_ACCOUNT_FAIL = "DELETE_USER_ACCOUNT_FAIL" 
export const DELETE_USER_ACCOUNT_RESET = "DELETE_USER_ACCOUNT_RESET" 

// user all address
export const GET_USER_ALL_ADDRESSES_REQUEST = "GET_USER_ALL_ADDRESSES_REQUEST"
export const GET_USER_ALL_ADDRESSES_SUCCESS = "GET_USER_ALL_ADDRESSES_SUCCESS"
export const GET_USER_ALL_ADDRESSES_FAIL = "GET_USER_ALL_ADDRESSES_FAIL"

// user single address details
export const GET_SINGLE_ADDRESS_REQUEST = "GET_SINGLE_ADDRESS_REQUEST"
export const GET_SINGLE_ADDRESS_SUCCESS = "GET_SINGLE_ADDRESS_SUCCESS"
export const GET_SINGLE_ADDRESS_FAIL = "GET_SINGLE_ADDRESS_FAIL"
export const GET_SINGLE_ADDRESS_RESET = "GET_SINGLE_ADDRESS_RESET"

// create address
export const CREATE_USER_ADDRESS_REQUEST = "CREATE_USER_ADDRESS_REQUEST"
export const CREATE_USER_ADDRESS_SUCCESS = "CREATE_USER_ADDRESS_SUCCESS"
export const CREATE_USER_ADDRESS_FAIL = "CREATE_USER_ADDRESS_FAIL"
export const CREATE_USER_ADDRESS_RESET = "CREATE_USER_ADDRESS_RESET"

// update address
export const UPDATE_USER_ADDRESS_REQUEST = "UPDATE_USER_ADDRESS_REQUEST"
export const UPDATE_USER_ADDRESS_SUCCESS = "UPDATE_USER_ADDRESS_SUCCESS"
export const UPDATE_USER_ADDRESS_FAIL = "UPDATE_USER_ADDRESS_FAIL"
export const UPDATE_USER_ADDRESS_RESET = "UPDATE_USER_ADDRESS_RESET"

// delete user address
export const DELETE_USER_ADDRESS_REQUEST = "DELETE_USER_ADDRESS_REQUEST"
export const DELETE_USER_ADDRESS_SUCCESS = "DELETE_USER_ADDRESS_SUCCESS"
export const DELETE_USER_ADDRESS_FAIL = "DELETE_USER_ADDRESS_FAIL"
export const DELETE_USER_ADDRESS_RESET = "DELETE_USER_ADDRESS_RESET"

// all orders list
export const GET_ALL_ORDERS_REQUEST = "GET_ALL_ORDERS_REQUEST"
export const GET_ALL_ORDERS_SUCCESS = "GET_ALL_ORDERS_SUCCESS"
export const GET_ALL_ORDERS_FAIL = "GET_ALL_ORDERS_FAIL"

// change order delivery status
export const CHANGE_DELIVERY_STATUS_REQUEST = "CHANGE_DELIVERY_STATUS_REQUEST"
export const CHANGE_DELIVERY_STATUS_SUCCESS = "CHANGE_DELIVERY_STATUS_SUCCESS"
export const CHANGE_DELIVERY_STATUS_FAIL = "CHANGE_DELIVERY_STATUS_FAIL"
export const CHANGE_DELIVERY_STATUS_RESET = "CHANGE_DELIVERY_STATUS_RESET"

// create mpesa transaction
export const MPESA_TRANSACTION_RESET = "MPESA_CREATE_RESET"

// STK push status
export const MPESA_STK_PUSH_REQUEST = "MPESA_STK_PUSH_REQUEST"
export const MPESA_STK_PUSH_FAIL = "MPESA_STK_PUSH_FAIL"
export const MPESA_STK_PUSH_SUCCESS = "MPESA_STK_PUSH_SUCCESS"

// call-back handler status
export const MPESA_CALLBACK_HANDLER_REQUEST = "MPESA_CALLBACK_HANDLER_REQUEST"
export const MPESA_CALLBACK_HANDLER_FAIL = "MPESA_CALLBACK_HANDLER_FAIL"
export const MPESA_CALLBACK_HANDLER_SUCCESS = "MPESA_CALLBACK_HANDLER_SUCCESS"

// add-to-cart status
export const ADD_TO_CART_REQUEST = "ADD_TO_CART_REQUEST"
export const ADD_TO_CART_SUCCESS = "ADD_TO_CART_SUCCESS"
export const ADD_TO_CART_FAIL = "ADD_TO_CART_FAIL"
export const ADD_TO_CART_RESET = "ADD_TO_CART_RESET"

// remove-from-cart status
export const REMOVE_FROM_CART_REQUEST= "REMOVE_FROM_CART_REQUEST"
export const REMOVE_FROM_CART_SUCCESS= "REMOVE_FROM_CART_SUCCESS"
export const REMOVE_FROM_CART_FAIL= "REMOVE_FROM_CART_FAIL"

// Loop from cart database
export const LOOP_FROM_CART_DATABASE_REQUEST= "LOOP_FROM_CART_DATABASE_REQUEST"
export const LOOP_FROM_CART_DATABASE_SUCCESS= "LOOP_FROM_CART_DATABASE_SUCCESS"
export const LOOP_FROM_CART_DATABASE_FAIL= "LOOP_FROM_CART_DATABASE_FAIL"

// Total-price
export const GET_TOTAL_PRICE_REQUEST="GET_TOTAL_PRICE_REQUEST"
export const GET_TOTAL_PRICE_SUCCESS="GET_TOTAL_PRICE_SUCCESS"
export const GET_TOTAL_PRICE_FAIL="GET_TOTAL_PRICE_FAIL"
